// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGSfPx9gslfTPxb4q1DtqHovVCWlSaLFA',
    appId: '1:553769191939:web:7b7fd70fbbeea131d41c36',
    messagingSenderId: '553769191939',
    projectId: 'todo-app-fdbbf',
    authDomain: 'todo-app-fdbbf.firebaseapp.com',
    storageBucket: 'todo-app-fdbbf.appspot.com',
    measurementId: 'G-VJ5F13C1ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBDeWwYUtKHJjo3xSyTxLOqggap30ayc',
    appId: '1:553769191939:android:f22e9a14634d1ce3d41c36',
    messagingSenderId: '553769191939',
    projectId: 'todo-app-fdbbf',
    storageBucket: 'todo-app-fdbbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf3RFXy-kPri6nmCvE6oiTb5lyc0cap2A',
    appId: '1:553769191939:ios:9484afa9827f7ddcd41c36',
    messagingSenderId: '553769191939',
    projectId: 'todo-app-fdbbf',
    storageBucket: 'todo-app-fdbbf.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf3RFXy-kPri6nmCvE6oiTb5lyc0cap2A',
    appId: '1:553769191939:ios:9edd71312b9b3d37d41c36',
    messagingSenderId: '553769191939',
    projectId: 'todo-app-fdbbf',
    storageBucket: 'todo-app-fdbbf.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
